//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Incident_Reporting_App_Server.RemoteAlarm {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Remote_Alarms_Web_ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Remote_Alarms_Web_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback User_SelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_InsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_Load_CompaniesOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_Load_CompanyBackUpOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_Load_Incoming_AlarmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_Load_Incoming_AlarmsVisibleOperationCompleted;
        
        private System.Threading.SendOrPostCallback User_Load_Incoming_Alarms_BackUPOperationCompleted;
        
        private System.Threading.SendOrPostCallback Company_SelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback Company_InsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback Company_UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Company_Status_UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Company_DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback Company_Alarms_SelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback Incoming_Alarms_InsertOperationCompleted;
        
        private System.Threading.SendOrPostCallback Incoming_Alarms_UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Incoming_Alarms_DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncomingAlarms_ChangeVisibilityOperationCompleted;
        
        private System.Threading.SendOrPostCallback IncomingAlarms_ChangeInVisibilityOperationCompleted;
        
        private System.Threading.SendOrPostCallback Incoming_Alarms_DeleteAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Server_DatetimeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Remote_Alarms_Web_Service() {
            this.Url = global::Incident_Reporting_App_Server.Properties.Settings.Default.Incident_Reporting_App_Server_WebReference_SC3_Alarm_Module_WS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event User_SelectCompletedEventHandler User_SelectCompleted;
        
        /// <remarks/>
        public event User_InsertCompletedEventHandler User_InsertCompleted;
        
        /// <remarks/>
        public event User_UpdateCompletedEventHandler User_UpdateCompleted;
        
        /// <remarks/>
        public event User_DeleteCompletedEventHandler User_DeleteCompleted;
        
        /// <remarks/>
        public event User_Load_CompaniesCompletedEventHandler User_Load_CompaniesCompleted;
        
        /// <remarks/>
        public event User_Load_CompanyBackUpCompletedEventHandler User_Load_CompanyBackUpCompleted;
        
        /// <remarks/>
        public event User_Load_Incoming_AlarmsCompletedEventHandler User_Load_Incoming_AlarmsCompleted;
        
        /// <remarks/>
        public event User_Load_Incoming_AlarmsVisibleCompletedEventHandler User_Load_Incoming_AlarmsVisibleCompleted;
        
        /// <remarks/>
        public event User_Load_Incoming_Alarms_BackUPCompletedEventHandler User_Load_Incoming_Alarms_BackUPCompleted;
        
        /// <remarks/>
        public event Company_SelectCompletedEventHandler Company_SelectCompleted;
        
        /// <remarks/>
        public event Company_InsertCompletedEventHandler Company_InsertCompleted;
        
        /// <remarks/>
        public event Company_UpdateCompletedEventHandler Company_UpdateCompleted;
        
        /// <remarks/>
        public event Company_Status_UpdateCompletedEventHandler Company_Status_UpdateCompleted;
        
        /// <remarks/>
        public event Company_DeleteCompletedEventHandler Company_DeleteCompleted;
        
        /// <remarks/>
        public event Company_Alarms_SelectCompletedEventHandler Company_Alarms_SelectCompleted;
        
        /// <remarks/>
        public event Incoming_Alarms_InsertCompletedEventHandler Incoming_Alarms_InsertCompleted;
        
        /// <remarks/>
        public event Incoming_Alarms_UpdateCompletedEventHandler Incoming_Alarms_UpdateCompleted;
        
        /// <remarks/>
        public event Incoming_Alarms_DeleteCompletedEventHandler Incoming_Alarms_DeleteCompleted;
        
        /// <remarks/>
        public event IncomingAlarms_ChangeVisibilityCompletedEventHandler IncomingAlarms_ChangeVisibilityCompleted;
        
        /// <remarks/>
        public event IncomingAlarms_ChangeInVisibilityCompletedEventHandler IncomingAlarms_ChangeInVisibilityCompleted;
        
        /// <remarks/>
        public event Incoming_Alarms_DeleteAllCompletedEventHandler Incoming_Alarms_DeleteAllCompleted;
        
        /// <remarks/>
        public event Get_Server_DatetimeCompletedEventHandler Get_Server_DatetimeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/User_Select", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User User_Select(string username, string password) {
            object[] results = this.Invoke("User_Select", new object[] {
                        username,
                        password});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void User_SelectAsync(string username, string password) {
            this.User_SelectAsync(username, password, null);
        }
        
        /// <remarks/>
        public void User_SelectAsync(string username, string password, object userState) {
            if ((this.User_SelectOperationCompleted == null)) {
                this.User_SelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_SelectOperationCompleted);
            }
            this.InvokeAsync("User_Select", new object[] {
                        username,
                        password}, this.User_SelectOperationCompleted, userState);
        }
        
        private void OnUser_SelectOperationCompleted(object arg) {
            if ((this.User_SelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_SelectCompleted(this, new User_SelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/User_Insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool User_Insert(User New_User) {
            object[] results = this.Invoke("User_Insert", new object[] {
                        New_User});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void User_InsertAsync(User New_User) {
            this.User_InsertAsync(New_User, null);
        }
        
        /// <remarks/>
        public void User_InsertAsync(User New_User, object userState) {
            if ((this.User_InsertOperationCompleted == null)) {
                this.User_InsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_InsertOperationCompleted);
            }
            this.InvokeAsync("User_Insert", new object[] {
                        New_User}, this.User_InsertOperationCompleted, userState);
        }
        
        private void OnUser_InsertOperationCompleted(object arg) {
            if ((this.User_InsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_InsertCompleted(this, new User_InsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/User_Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool User_Update(User Edited_User) {
            object[] results = this.Invoke("User_Update", new object[] {
                        Edited_User});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void User_UpdateAsync(User Edited_User) {
            this.User_UpdateAsync(Edited_User, null);
        }
        
        /// <remarks/>
        public void User_UpdateAsync(User Edited_User, object userState) {
            if ((this.User_UpdateOperationCompleted == null)) {
                this.User_UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_UpdateOperationCompleted);
            }
            this.InvokeAsync("User_Update", new object[] {
                        Edited_User}, this.User_UpdateOperationCompleted, userState);
        }
        
        private void OnUser_UpdateOperationCompleted(object arg) {
            if ((this.User_UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_UpdateCompleted(this, new User_UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/User_Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool User_Delete(User Deleted_User) {
            object[] results = this.Invoke("User_Delete", new object[] {
                        Deleted_User});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void User_DeleteAsync(User Deleted_User) {
            this.User_DeleteAsync(Deleted_User, null);
        }
        
        /// <remarks/>
        public void User_DeleteAsync(User Deleted_User, object userState) {
            if ((this.User_DeleteOperationCompleted == null)) {
                this.User_DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_DeleteOperationCompleted);
            }
            this.InvokeAsync("User_Delete", new object[] {
                        Deleted_User}, this.User_DeleteOperationCompleted, userState);
        }
        
        private void OnUser_DeleteOperationCompleted(object arg) {
            if ((this.User_DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_DeleteCompleted(this, new User_DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/User_Load_Companies", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Company[] User_Load_Companies(int User_id, string Username, string Password) {
            object[] results = this.Invoke("User_Load_Companies", new object[] {
                        User_id,
                        Username,
                        Password});
            return ((Company[])(results[0]));
        }
        
        /// <remarks/>
        public void User_Load_CompaniesAsync(int User_id, string Username, string Password) {
            this.User_Load_CompaniesAsync(User_id, Username, Password, null);
        }
        
        /// <remarks/>
        public void User_Load_CompaniesAsync(int User_id, string Username, string Password, object userState) {
            if ((this.User_Load_CompaniesOperationCompleted == null)) {
                this.User_Load_CompaniesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_Load_CompaniesOperationCompleted);
            }
            this.InvokeAsync("User_Load_Companies", new object[] {
                        User_id,
                        Username,
                        Password}, this.User_Load_CompaniesOperationCompleted, userState);
        }
        
        private void OnUser_Load_CompaniesOperationCompleted(object arg) {
            if ((this.User_Load_CompaniesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_Load_CompaniesCompleted(this, new User_Load_CompaniesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/User_Load_CompanyBackUp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Company_Backup[] User_Load_CompanyBackUp(int User_id, string Username, string Password) {
            object[] results = this.Invoke("User_Load_CompanyBackUp", new object[] {
                        User_id,
                        Username,
                        Password});
            return ((Company_Backup[])(results[0]));
        }
        
        /// <remarks/>
        public void User_Load_CompanyBackUpAsync(int User_id, string Username, string Password) {
            this.User_Load_CompanyBackUpAsync(User_id, Username, Password, null);
        }
        
        /// <remarks/>
        public void User_Load_CompanyBackUpAsync(int User_id, string Username, string Password, object userState) {
            if ((this.User_Load_CompanyBackUpOperationCompleted == null)) {
                this.User_Load_CompanyBackUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_Load_CompanyBackUpOperationCompleted);
            }
            this.InvokeAsync("User_Load_CompanyBackUp", new object[] {
                        User_id,
                        Username,
                        Password}, this.User_Load_CompanyBackUpOperationCompleted, userState);
        }
        
        private void OnUser_Load_CompanyBackUpOperationCompleted(object arg) {
            if ((this.User_Load_CompanyBackUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_Load_CompanyBackUpCompleted(this, new User_Load_CompanyBackUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/User_Load_Incoming_Alarms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public IncomingAlarm[] User_Load_Incoming_Alarms(int User_id, string Username, string Password) {
            object[] results = this.Invoke("User_Load_Incoming_Alarms", new object[] {
                        User_id,
                        Username,
                        Password});
            return ((IncomingAlarm[])(results[0]));
        }
        
        /// <remarks/>
        public void User_Load_Incoming_AlarmsAsync(int User_id, string Username, string Password) {
            this.User_Load_Incoming_AlarmsAsync(User_id, Username, Password, null);
        }
        
        /// <remarks/>
        public void User_Load_Incoming_AlarmsAsync(int User_id, string Username, string Password, object userState) {
            if ((this.User_Load_Incoming_AlarmsOperationCompleted == null)) {
                this.User_Load_Incoming_AlarmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_Load_Incoming_AlarmsOperationCompleted);
            }
            this.InvokeAsync("User_Load_Incoming_Alarms", new object[] {
                        User_id,
                        Username,
                        Password}, this.User_Load_Incoming_AlarmsOperationCompleted, userState);
        }
        
        private void OnUser_Load_Incoming_AlarmsOperationCompleted(object arg) {
            if ((this.User_Load_Incoming_AlarmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_Load_Incoming_AlarmsCompleted(this, new User_Load_Incoming_AlarmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/User_Load_Incoming_AlarmsVisible", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public IncomingAlarm[] User_Load_Incoming_AlarmsVisible(int User_id, string Username, string Password) {
            object[] results = this.Invoke("User_Load_Incoming_AlarmsVisible", new object[] {
                        User_id,
                        Username,
                        Password});
            return ((IncomingAlarm[])(results[0]));
        }
        
        /// <remarks/>
        public void User_Load_Incoming_AlarmsVisibleAsync(int User_id, string Username, string Password) {
            this.User_Load_Incoming_AlarmsVisibleAsync(User_id, Username, Password, null);
        }
        
        /// <remarks/>
        public void User_Load_Incoming_AlarmsVisibleAsync(int User_id, string Username, string Password, object userState) {
            if ((this.User_Load_Incoming_AlarmsVisibleOperationCompleted == null)) {
                this.User_Load_Incoming_AlarmsVisibleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_Load_Incoming_AlarmsVisibleOperationCompleted);
            }
            this.InvokeAsync("User_Load_Incoming_AlarmsVisible", new object[] {
                        User_id,
                        Username,
                        Password}, this.User_Load_Incoming_AlarmsVisibleOperationCompleted, userState);
        }
        
        private void OnUser_Load_Incoming_AlarmsVisibleOperationCompleted(object arg) {
            if ((this.User_Load_Incoming_AlarmsVisibleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_Load_Incoming_AlarmsVisibleCompleted(this, new User_Load_Incoming_AlarmsVisibleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/User_Load_Incoming_Alarms_BackUP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public IncomingAlarm_Backup[] User_Load_Incoming_Alarms_BackUP(int User_id, string Username, string Password) {
            object[] results = this.Invoke("User_Load_Incoming_Alarms_BackUP", new object[] {
                        User_id,
                        Username,
                        Password});
            return ((IncomingAlarm_Backup[])(results[0]));
        }
        
        /// <remarks/>
        public void User_Load_Incoming_Alarms_BackUPAsync(int User_id, string Username, string Password) {
            this.User_Load_Incoming_Alarms_BackUPAsync(User_id, Username, Password, null);
        }
        
        /// <remarks/>
        public void User_Load_Incoming_Alarms_BackUPAsync(int User_id, string Username, string Password, object userState) {
            if ((this.User_Load_Incoming_Alarms_BackUPOperationCompleted == null)) {
                this.User_Load_Incoming_Alarms_BackUPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUser_Load_Incoming_Alarms_BackUPOperationCompleted);
            }
            this.InvokeAsync("User_Load_Incoming_Alarms_BackUP", new object[] {
                        User_id,
                        Username,
                        Password}, this.User_Load_Incoming_Alarms_BackUPOperationCompleted, userState);
        }
        
        private void OnUser_Load_Incoming_Alarms_BackUPOperationCompleted(object arg) {
            if ((this.User_Load_Incoming_Alarms_BackUPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.User_Load_Incoming_Alarms_BackUPCompleted(this, new User_Load_Incoming_Alarms_BackUPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Company_Select", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Company Company_Select(int User_id, string Username, string Password, int Radio_ID) {
            object[] results = this.Invoke("Company_Select", new object[] {
                        User_id,
                        Username,
                        Password,
                        Radio_ID});
            return ((Company)(results[0]));
        }
        
        /// <remarks/>
        public void Company_SelectAsync(int User_id, string Username, string Password, int Radio_ID) {
            this.Company_SelectAsync(User_id, Username, Password, Radio_ID, null);
        }
        
        /// <remarks/>
        public void Company_SelectAsync(int User_id, string Username, string Password, int Radio_ID, object userState) {
            if ((this.Company_SelectOperationCompleted == null)) {
                this.Company_SelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompany_SelectOperationCompleted);
            }
            this.InvokeAsync("Company_Select", new object[] {
                        User_id,
                        Username,
                        Password,
                        Radio_ID}, this.Company_SelectOperationCompleted, userState);
        }
        
        private void OnCompany_SelectOperationCompleted(object arg) {
            if ((this.Company_SelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Company_SelectCompleted(this, new Company_SelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Company_Insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Company_Insert(int User_id, string Username, string Password, Company New_Company) {
            object[] results = this.Invoke("Company_Insert", new object[] {
                        User_id,
                        Username,
                        Password,
                        New_Company});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Company_InsertAsync(int User_id, string Username, string Password, Company New_Company) {
            this.Company_InsertAsync(User_id, Username, Password, New_Company, null);
        }
        
        /// <remarks/>
        public void Company_InsertAsync(int User_id, string Username, string Password, Company New_Company, object userState) {
            if ((this.Company_InsertOperationCompleted == null)) {
                this.Company_InsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompany_InsertOperationCompleted);
            }
            this.InvokeAsync("Company_Insert", new object[] {
                        User_id,
                        Username,
                        Password,
                        New_Company}, this.Company_InsertOperationCompleted, userState);
        }
        
        private void OnCompany_InsertOperationCompleted(object arg) {
            if ((this.Company_InsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Company_InsertCompleted(this, new Company_InsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Company_Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Company_Update(int User_id, string Username, string Password, Company Edited_Company) {
            object[] results = this.Invoke("Company_Update", new object[] {
                        User_id,
                        Username,
                        Password,
                        Edited_Company});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Company_UpdateAsync(int User_id, string Username, string Password, Company Edited_Company) {
            this.Company_UpdateAsync(User_id, Username, Password, Edited_Company, null);
        }
        
        /// <remarks/>
        public void Company_UpdateAsync(int User_id, string Username, string Password, Company Edited_Company, object userState) {
            if ((this.Company_UpdateOperationCompleted == null)) {
                this.Company_UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompany_UpdateOperationCompleted);
            }
            this.InvokeAsync("Company_Update", new object[] {
                        User_id,
                        Username,
                        Password,
                        Edited_Company}, this.Company_UpdateOperationCompleted, userState);
        }
        
        private void OnCompany_UpdateOperationCompleted(object arg) {
            if ((this.Company_UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Company_UpdateCompleted(this, new Company_UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Company_Status_Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Company_Status_Update(string Username, string Password, string OnlineAlarmUnits, string OfflineAlarmUnits, System.DateTime Check_DateTime) {
            object[] results = this.Invoke("Company_Status_Update", new object[] {
                        Username,
                        Password,
                        OnlineAlarmUnits,
                        OfflineAlarmUnits,
                        Check_DateTime});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Company_Status_UpdateAsync(string Username, string Password, string OnlineAlarmUnits, string OfflineAlarmUnits, System.DateTime Check_DateTime) {
            this.Company_Status_UpdateAsync(Username, Password, OnlineAlarmUnits, OfflineAlarmUnits, Check_DateTime, null);
        }
        
        /// <remarks/>
        public void Company_Status_UpdateAsync(string Username, string Password, string OnlineAlarmUnits, string OfflineAlarmUnits, System.DateTime Check_DateTime, object userState) {
            if ((this.Company_Status_UpdateOperationCompleted == null)) {
                this.Company_Status_UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompany_Status_UpdateOperationCompleted);
            }
            this.InvokeAsync("Company_Status_Update", new object[] {
                        Username,
                        Password,
                        OnlineAlarmUnits,
                        OfflineAlarmUnits,
                        Check_DateTime}, this.Company_Status_UpdateOperationCompleted, userState);
        }
        
        private void OnCompany_Status_UpdateOperationCompleted(object arg) {
            if ((this.Company_Status_UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Company_Status_UpdateCompleted(this, new Company_Status_UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Company_Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Company_Delete(int User_id, string Username, string Password, int Company_Id) {
            object[] results = this.Invoke("Company_Delete", new object[] {
                        User_id,
                        Username,
                        Password,
                        Company_Id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Company_DeleteAsync(int User_id, string Username, string Password, int Company_Id) {
            this.Company_DeleteAsync(User_id, Username, Password, Company_Id, null);
        }
        
        /// <remarks/>
        public void Company_DeleteAsync(int User_id, string Username, string Password, int Company_Id, object userState) {
            if ((this.Company_DeleteOperationCompleted == null)) {
                this.Company_DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompany_DeleteOperationCompleted);
            }
            this.InvokeAsync("Company_Delete", new object[] {
                        User_id,
                        Username,
                        Password,
                        Company_Id}, this.Company_DeleteOperationCompleted, userState);
        }
        
        private void OnCompany_DeleteOperationCompleted(object arg) {
            if ((this.Company_DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Company_DeleteCompleted(this, new Company_DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Company_Alarms_Select", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public IncomingAlarm[] Company_Alarms_Select(int User_id, string Username, string Password, int Radio_Number) {
            object[] results = this.Invoke("Company_Alarms_Select", new object[] {
                        User_id,
                        Username,
                        Password,
                        Radio_Number});
            return ((IncomingAlarm[])(results[0]));
        }
        
        /// <remarks/>
        public void Company_Alarms_SelectAsync(int User_id, string Username, string Password, int Radio_Number) {
            this.Company_Alarms_SelectAsync(User_id, Username, Password, Radio_Number, null);
        }
        
        /// <remarks/>
        public void Company_Alarms_SelectAsync(int User_id, string Username, string Password, int Radio_Number, object userState) {
            if ((this.Company_Alarms_SelectOperationCompleted == null)) {
                this.Company_Alarms_SelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompany_Alarms_SelectOperationCompleted);
            }
            this.InvokeAsync("Company_Alarms_Select", new object[] {
                        User_id,
                        Username,
                        Password,
                        Radio_Number}, this.Company_Alarms_SelectOperationCompleted, userState);
        }
        
        private void OnCompany_Alarms_SelectOperationCompleted(object arg) {
            if ((this.Company_Alarms_SelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Company_Alarms_SelectCompleted(this, new Company_Alarms_SelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Incoming_Alarms_Insert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Incoming_Alarms_Insert(string Username, string Password, IncomingAlarm New_Incoming_Alarm) {
            object[] results = this.Invoke("Incoming_Alarms_Insert", new object[] {
                        Username,
                        Password,
                        New_Incoming_Alarm});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Incoming_Alarms_InsertAsync(string Username, string Password, IncomingAlarm New_Incoming_Alarm) {
            this.Incoming_Alarms_InsertAsync(Username, Password, New_Incoming_Alarm, null);
        }
        
        /// <remarks/>
        public void Incoming_Alarms_InsertAsync(string Username, string Password, IncomingAlarm New_Incoming_Alarm, object userState) {
            if ((this.Incoming_Alarms_InsertOperationCompleted == null)) {
                this.Incoming_Alarms_InsertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncoming_Alarms_InsertOperationCompleted);
            }
            this.InvokeAsync("Incoming_Alarms_Insert", new object[] {
                        Username,
                        Password,
                        New_Incoming_Alarm}, this.Incoming_Alarms_InsertOperationCompleted, userState);
        }
        
        private void OnIncoming_Alarms_InsertOperationCompleted(object arg) {
            if ((this.Incoming_Alarms_InsertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Incoming_Alarms_InsertCompleted(this, new Incoming_Alarms_InsertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Incoming_Alarms_Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Incoming_Alarms_Update(string Username, string Password, IncomingAlarm Edited_Incoming_Alarm) {
            object[] results = this.Invoke("Incoming_Alarms_Update", new object[] {
                        Username,
                        Password,
                        Edited_Incoming_Alarm});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Incoming_Alarms_UpdateAsync(string Username, string Password, IncomingAlarm Edited_Incoming_Alarm) {
            this.Incoming_Alarms_UpdateAsync(Username, Password, Edited_Incoming_Alarm, null);
        }
        
        /// <remarks/>
        public void Incoming_Alarms_UpdateAsync(string Username, string Password, IncomingAlarm Edited_Incoming_Alarm, object userState) {
            if ((this.Incoming_Alarms_UpdateOperationCompleted == null)) {
                this.Incoming_Alarms_UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncoming_Alarms_UpdateOperationCompleted);
            }
            this.InvokeAsync("Incoming_Alarms_Update", new object[] {
                        Username,
                        Password,
                        Edited_Incoming_Alarm}, this.Incoming_Alarms_UpdateOperationCompleted, userState);
        }
        
        private void OnIncoming_Alarms_UpdateOperationCompleted(object arg) {
            if ((this.Incoming_Alarms_UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Incoming_Alarms_UpdateCompleted(this, new Incoming_Alarms_UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Incoming_Alarms_Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Incoming_Alarms_Delete(int User_id, string Username, string Password, int Alarm_Id) {
            object[] results = this.Invoke("Incoming_Alarms_Delete", new object[] {
                        User_id,
                        Username,
                        Password,
                        Alarm_Id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Incoming_Alarms_DeleteAsync(int User_id, string Username, string Password, int Alarm_Id) {
            this.Incoming_Alarms_DeleteAsync(User_id, Username, Password, Alarm_Id, null);
        }
        
        /// <remarks/>
        public void Incoming_Alarms_DeleteAsync(int User_id, string Username, string Password, int Alarm_Id, object userState) {
            if ((this.Incoming_Alarms_DeleteOperationCompleted == null)) {
                this.Incoming_Alarms_DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncoming_Alarms_DeleteOperationCompleted);
            }
            this.InvokeAsync("Incoming_Alarms_Delete", new object[] {
                        User_id,
                        Username,
                        Password,
                        Alarm_Id}, this.Incoming_Alarms_DeleteOperationCompleted, userState);
        }
        
        private void OnIncoming_Alarms_DeleteOperationCompleted(object arg) {
            if ((this.Incoming_Alarms_DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Incoming_Alarms_DeleteCompleted(this, new Incoming_Alarms_DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncomingAlarms_ChangeVisibility", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IncomingAlarms_ChangeVisibility(int User_id, string Username, string Password) {
            object[] results = this.Invoke("IncomingAlarms_ChangeVisibility", new object[] {
                        User_id,
                        Username,
                        Password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IncomingAlarms_ChangeVisibilityAsync(int User_id, string Username, string Password) {
            this.IncomingAlarms_ChangeVisibilityAsync(User_id, Username, Password, null);
        }
        
        /// <remarks/>
        public void IncomingAlarms_ChangeVisibilityAsync(int User_id, string Username, string Password, object userState) {
            if ((this.IncomingAlarms_ChangeVisibilityOperationCompleted == null)) {
                this.IncomingAlarms_ChangeVisibilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncomingAlarms_ChangeVisibilityOperationCompleted);
            }
            this.InvokeAsync("IncomingAlarms_ChangeVisibility", new object[] {
                        User_id,
                        Username,
                        Password}, this.IncomingAlarms_ChangeVisibilityOperationCompleted, userState);
        }
        
        private void OnIncomingAlarms_ChangeVisibilityOperationCompleted(object arg) {
            if ((this.IncomingAlarms_ChangeVisibilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncomingAlarms_ChangeVisibilityCompleted(this, new IncomingAlarms_ChangeVisibilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IncomingAlarms_ChangeInVisibility", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IncomingAlarms_ChangeInVisibility(int User_id, string Username, string Password, System.DateTime From_DateTime, System.DateTime To_DateTime) {
            object[] results = this.Invoke("IncomingAlarms_ChangeInVisibility", new object[] {
                        User_id,
                        Username,
                        Password,
                        From_DateTime,
                        To_DateTime});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IncomingAlarms_ChangeInVisibilityAsync(int User_id, string Username, string Password, System.DateTime From_DateTime, System.DateTime To_DateTime) {
            this.IncomingAlarms_ChangeInVisibilityAsync(User_id, Username, Password, From_DateTime, To_DateTime, null);
        }
        
        /// <remarks/>
        public void IncomingAlarms_ChangeInVisibilityAsync(int User_id, string Username, string Password, System.DateTime From_DateTime, System.DateTime To_DateTime, object userState) {
            if ((this.IncomingAlarms_ChangeInVisibilityOperationCompleted == null)) {
                this.IncomingAlarms_ChangeInVisibilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncomingAlarms_ChangeInVisibilityOperationCompleted);
            }
            this.InvokeAsync("IncomingAlarms_ChangeInVisibility", new object[] {
                        User_id,
                        Username,
                        Password,
                        From_DateTime,
                        To_DateTime}, this.IncomingAlarms_ChangeInVisibilityOperationCompleted, userState);
        }
        
        private void OnIncomingAlarms_ChangeInVisibilityOperationCompleted(object arg) {
            if ((this.IncomingAlarms_ChangeInVisibilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncomingAlarms_ChangeInVisibilityCompleted(this, new IncomingAlarms_ChangeInVisibilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Incoming_Alarms_DeleteAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Incoming_Alarms_DeleteAll(int User_id, string Username, string Password) {
            object[] results = this.Invoke("Incoming_Alarms_DeleteAll", new object[] {
                        User_id,
                        Username,
                        Password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Incoming_Alarms_DeleteAllAsync(int User_id, string Username, string Password) {
            this.Incoming_Alarms_DeleteAllAsync(User_id, Username, Password, null);
        }
        
        /// <remarks/>
        public void Incoming_Alarms_DeleteAllAsync(int User_id, string Username, string Password, object userState) {
            if ((this.Incoming_Alarms_DeleteAllOperationCompleted == null)) {
                this.Incoming_Alarms_DeleteAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncoming_Alarms_DeleteAllOperationCompleted);
            }
            this.InvokeAsync("Incoming_Alarms_DeleteAll", new object[] {
                        User_id,
                        Username,
                        Password}, this.Incoming_Alarms_DeleteAllOperationCompleted, userState);
        }
        
        private void OnIncoming_Alarms_DeleteAllOperationCompleted(object arg) {
            if ((this.Incoming_Alarms_DeleteAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Incoming_Alarms_DeleteAllCompleted(this, new Incoming_Alarms_DeleteAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Server_Datetime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime Get_Server_Datetime() {
            object[] results = this.Invoke("Get_Server_Datetime", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Server_DatetimeAsync() {
            this.Get_Server_DatetimeAsync(null);
        }
        
        /// <remarks/>
        public void Get_Server_DatetimeAsync(object userState) {
            if ((this.Get_Server_DatetimeOperationCompleted == null)) {
                this.Get_Server_DatetimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Server_DatetimeOperationCompleted);
            }
            this.InvokeAsync("Get_Server_Datetime", new object[0], this.Get_Server_DatetimeOperationCompleted, userState);
        }
        
        private void OnGet_Server_DatetimeOperationCompleted(object arg) {
            if ((this.Get_Server_DatetimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Server_DatetimeCompleted(this, new Get_Server_DatetimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User {
        
        private int user_idField;
        
        private string usernameField;
        
        private string passwordField;
        
        private int privilegeField;
        
        private bool goodField;
        
        private Company[] companiesField;
        
        private IncomingAlarm[] incoming_AlarmsField;
        
        /// <remarks/>
        public int User_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int Privilege {
            get {
                return this.privilegeField;
            }
            set {
                this.privilegeField = value;
            }
        }
        
        /// <remarks/>
        public bool Good {
            get {
                return this.goodField;
            }
            set {
                this.goodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Company[] Companies {
            get {
                return this.companiesField;
            }
            set {
                this.companiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public IncomingAlarm[] Incoming_Alarms {
            get {
                return this.incoming_AlarmsField;
            }
            set {
                this.incoming_AlarmsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Company {
        
        private int idField;
        
        private double radioIDField;
        
        private int u_idField;
        
        private string companyNameField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string contactPersonNameField;
        
        private string landLinePhoneNumberField;
        
        private string mobileNumberOneField;
        
        private string addressLineOneField;
        
        private string addressLineTwoField;
        
        private string companyTypeField;
        
        private int systemCheckField;
        
        private System.DateTime systemCheckedDateField;
        
        private string mobileNumberTwoField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public double RadioID {
            get {
                return this.radioIDField;
            }
            set {
                this.radioIDField = value;
            }
        }
        
        /// <remarks/>
        public int U_id {
            get {
                return this.u_idField;
            }
            set {
                this.u_idField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string ContactPersonName {
            get {
                return this.contactPersonNameField;
            }
            set {
                this.contactPersonNameField = value;
            }
        }
        
        /// <remarks/>
        public string LandLinePhoneNumber {
            get {
                return this.landLinePhoneNumberField;
            }
            set {
                this.landLinePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MobileNumberOne {
            get {
                return this.mobileNumberOneField;
            }
            set {
                this.mobileNumberOneField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLineOne {
            get {
                return this.addressLineOneField;
            }
            set {
                this.addressLineOneField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLineTwo {
            get {
                return this.addressLineTwoField;
            }
            set {
                this.addressLineTwoField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyType {
            get {
                return this.companyTypeField;
            }
            set {
                this.companyTypeField = value;
            }
        }
        
        /// <remarks/>
        public int SystemCheck {
            get {
                return this.systemCheckField;
            }
            set {
                this.systemCheckField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SystemCheckedDate {
            get {
                return this.systemCheckedDateField;
            }
            set {
                this.systemCheckedDateField = value;
            }
        }
        
        /// <remarks/>
        public string MobileNumberTwo {
            get {
                return this.mobileNumberTwoField;
            }
            set {
                this.mobileNumberTwoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IncomingAlarm_Backup {
        
        private int idField;
        
        private int radioIDField;
        
        private int company_IDField;
        
        private string alarmTypeField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private System.DateTime dateReceivedField;
        
        private int acknowledegeField;
        
        private System.DateTime acknowledegeDateField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int RadioID {
            get {
                return this.radioIDField;
            }
            set {
                this.radioIDField = value;
            }
        }
        
        /// <remarks/>
        public int Company_ID {
            get {
                return this.company_IDField;
            }
            set {
                this.company_IDField = value;
            }
        }
        
        /// <remarks/>
        public string AlarmType {
            get {
                return this.alarmTypeField;
            }
            set {
                this.alarmTypeField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateReceived {
            get {
                return this.dateReceivedField;
            }
            set {
                this.dateReceivedField = value;
            }
        }
        
        /// <remarks/>
        public int Acknowledege {
            get {
                return this.acknowledegeField;
            }
            set {
                this.acknowledegeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AcknowledegeDate {
            get {
                return this.acknowledegeDateField;
            }
            set {
                this.acknowledegeDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Company_Backup {
        
        private int idField;
        
        private int radioIDField;
        
        private int u_idField;
        
        private string companyNameField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string contactPersonNameField;
        
        private string landLinePhoneNumberField;
        
        private string mobileNumberOneField;
        
        private string addressLineOneField;
        
        private string addressLineTwoField;
        
        private string companyTypeField;
        
        private int systemCheckField;
        
        private System.DateTime systemCheckedDateField;
        
        private string mobileNumberTwoField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int RadioID {
            get {
                return this.radioIDField;
            }
            set {
                this.radioIDField = value;
            }
        }
        
        /// <remarks/>
        public int U_id {
            get {
                return this.u_idField;
            }
            set {
                this.u_idField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string ContactPersonName {
            get {
                return this.contactPersonNameField;
            }
            set {
                this.contactPersonNameField = value;
            }
        }
        
        /// <remarks/>
        public string LandLinePhoneNumber {
            get {
                return this.landLinePhoneNumberField;
            }
            set {
                this.landLinePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MobileNumberOne {
            get {
                return this.mobileNumberOneField;
            }
            set {
                this.mobileNumberOneField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLineOne {
            get {
                return this.addressLineOneField;
            }
            set {
                this.addressLineOneField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLineTwo {
            get {
                return this.addressLineTwoField;
            }
            set {
                this.addressLineTwoField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyType {
            get {
                return this.companyTypeField;
            }
            set {
                this.companyTypeField = value;
            }
        }
        
        /// <remarks/>
        public int SystemCheck {
            get {
                return this.systemCheckField;
            }
            set {
                this.systemCheckField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SystemCheckedDate {
            get {
                return this.systemCheckedDateField;
            }
            set {
                this.systemCheckedDateField = value;
            }
        }
        
        /// <remarks/>
        public string MobileNumberTwo {
            get {
                return this.mobileNumberTwoField;
            }
            set {
                this.mobileNumberTwoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IncomingAlarm {
        
        private int idField;
        
        private double radioIDField;
        
        private int company_IDField;
        
        private string alarmTypeField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private System.DateTime dateReceivedField;
        
        private int acknowledegeField;
        
        private System.DateTime acknowledegeDateField;
        
        private bool visibilityField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public double RadioID {
            get {
                return this.radioIDField;
            }
            set {
                this.radioIDField = value;
            }
        }
        
        /// <remarks/>
        public int Company_ID {
            get {
                return this.company_IDField;
            }
            set {
                this.company_IDField = value;
            }
        }
        
        /// <remarks/>
        public string AlarmType {
            get {
                return this.alarmTypeField;
            }
            set {
                this.alarmTypeField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateReceived {
            get {
                return this.dateReceivedField;
            }
            set {
                this.dateReceivedField = value;
            }
        }
        
        /// <remarks/>
        public int Acknowledege {
            get {
                return this.acknowledegeField;
            }
            set {
                this.acknowledegeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AcknowledegeDate {
            get {
                return this.acknowledegeDateField;
            }
            set {
                this.acknowledegeDateField = value;
            }
        }
        
        /// <remarks/>
        public bool Visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void User_SelectCompletedEventHandler(object sender, User_SelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void User_InsertCompletedEventHandler(object sender, User_InsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_InsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_InsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void User_UpdateCompletedEventHandler(object sender, User_UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void User_DeleteCompletedEventHandler(object sender, User_DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void User_Load_CompaniesCompletedEventHandler(object sender, User_Load_CompaniesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_Load_CompaniesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_Load_CompaniesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Company[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Company[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void User_Load_CompanyBackUpCompletedEventHandler(object sender, User_Load_CompanyBackUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_Load_CompanyBackUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_Load_CompanyBackUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Company_Backup[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Company_Backup[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void User_Load_Incoming_AlarmsCompletedEventHandler(object sender, User_Load_Incoming_AlarmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_Load_Incoming_AlarmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_Load_Incoming_AlarmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IncomingAlarm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IncomingAlarm[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void User_Load_Incoming_AlarmsVisibleCompletedEventHandler(object sender, User_Load_Incoming_AlarmsVisibleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_Load_Incoming_AlarmsVisibleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_Load_Incoming_AlarmsVisibleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IncomingAlarm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IncomingAlarm[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void User_Load_Incoming_Alarms_BackUPCompletedEventHandler(object sender, User_Load_Incoming_Alarms_BackUPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class User_Load_Incoming_Alarms_BackUPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal User_Load_Incoming_Alarms_BackUPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IncomingAlarm_Backup[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IncomingAlarm_Backup[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Company_SelectCompletedEventHandler(object sender, Company_SelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Company_SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Company_SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Company Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Company)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Company_InsertCompletedEventHandler(object sender, Company_InsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Company_InsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Company_InsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Company_UpdateCompletedEventHandler(object sender, Company_UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Company_UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Company_UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Company_Status_UpdateCompletedEventHandler(object sender, Company_Status_UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Company_Status_UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Company_Status_UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Company_DeleteCompletedEventHandler(object sender, Company_DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Company_DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Company_DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Company_Alarms_SelectCompletedEventHandler(object sender, Company_Alarms_SelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Company_Alarms_SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Company_Alarms_SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IncomingAlarm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IncomingAlarm[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Incoming_Alarms_InsertCompletedEventHandler(object sender, Incoming_Alarms_InsertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Incoming_Alarms_InsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Incoming_Alarms_InsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Incoming_Alarms_UpdateCompletedEventHandler(object sender, Incoming_Alarms_UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Incoming_Alarms_UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Incoming_Alarms_UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Incoming_Alarms_DeleteCompletedEventHandler(object sender, Incoming_Alarms_DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Incoming_Alarms_DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Incoming_Alarms_DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IncomingAlarms_ChangeVisibilityCompletedEventHandler(object sender, IncomingAlarms_ChangeVisibilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncomingAlarms_ChangeVisibilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncomingAlarms_ChangeVisibilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IncomingAlarms_ChangeInVisibilityCompletedEventHandler(object sender, IncomingAlarms_ChangeInVisibilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncomingAlarms_ChangeInVisibilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncomingAlarms_ChangeInVisibilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Incoming_Alarms_DeleteAllCompletedEventHandler(object sender, Incoming_Alarms_DeleteAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Incoming_Alarms_DeleteAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Incoming_Alarms_DeleteAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Get_Server_DatetimeCompletedEventHandler(object sender, Get_Server_DatetimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Server_DatetimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Server_DatetimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591