//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC3_Alarm_Module.SC3ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int User_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private int PrivilegeField;
        
        private bool Is_AdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Username_EditedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Password_EditedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int User_id {
            get {
                return this.User_idField;
            }
            set {
                if ((this.User_idField.Equals(value) != true)) {
                    this.User_idField = value;
                    this.RaisePropertyChanged("User_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Privilege {
            get {
                return this.PrivilegeField;
            }
            set {
                if ((this.PrivilegeField.Equals(value) != true)) {
                    this.PrivilegeField = value;
                    this.RaisePropertyChanged("Privilege");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool Is_Admin {
            get {
                return this.Is_AdminField;
            }
            set {
                if ((this.Is_AdminField.Equals(value) != true)) {
                    this.Is_AdminField = value;
                    this.RaisePropertyChanged("Is_Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Username_Edited {
            get {
                return this.Username_EditedField;
            }
            set {
                if ((object.ReferenceEquals(this.Username_EditedField, value) != true)) {
                    this.Username_EditedField = value;
                    this.RaisePropertyChanged("Username_Edited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password_Edited {
            get {
                return this.Password_EditedField;
            }
            set {
                if ((object.ReferenceEquals(this.Password_EditedField, value) != true)) {
                    this.Password_EditedField = value;
                    this.RaisePropertyChanged("Password_Edited");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SC3ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SC3_Alarm_Module.SC3ServiceReference1.HelloWorldResponse HelloWorld(SC3_Alarm_Module.SC3ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SC3_Alarm_Module.SC3ServiceReference1.HelloWorldResponse> HelloWorldAsync(SC3_Alarm_Module.SC3ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_User", ReplyAction="*")]
        SC3_Alarm_Module.SC3ServiceReference1.Select_UserResponse Select_User(SC3_Alarm_Module.SC3ServiceReference1.Select_UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_User", ReplyAction="*")]
        System.Threading.Tasks.Task<SC3_Alarm_Module.SC3ServiceReference1.Select_UserResponse> Select_UserAsync(SC3_Alarm_Module.SC3ServiceReference1.Select_UserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Us", ReplyAction="*")]
        SC3_Alarm_Module.SC3ServiceReference1.Delete_UsResponse Delete_Us(SC3_Alarm_Module.SC3ServiceReference1.Delete_UsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Us", ReplyAction="*")]
        System.Threading.Tasks.Task<SC3_Alarm_Module.SC3ServiceReference1.Delete_UsResponse> Delete_UsAsync(SC3_Alarm_Module.SC3ServiceReference1.Delete_UsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SC3_Alarm_Module.SC3ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SC3_Alarm_Module.SC3ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SC3_Alarm_Module.SC3ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SC3_Alarm_Module.SC3ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Select_UserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select_User", Namespace="http://tempuri.org/", Order=0)]
        public SC3_Alarm_Module.SC3ServiceReference1.Select_UserRequestBody Body;
        
        public Select_UserRequest() {
        }
        
        public Select_UserRequest(SC3_Alarm_Module.SC3ServiceReference1.Select_UserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Select_UserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public Select_UserRequestBody() {
        }
        
        public Select_UserRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Select_UserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select_UserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SC3_Alarm_Module.SC3ServiceReference1.Select_UserResponseBody Body;
        
        public Select_UserResponse() {
        }
        
        public Select_UserResponse(SC3_Alarm_Module.SC3ServiceReference1.Select_UserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Select_UserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SC3_Alarm_Module.SC3ServiceReference1.User Select_UserResult;
        
        public Select_UserResponseBody() {
        }
        
        public Select_UserResponseBody(SC3_Alarm_Module.SC3ServiceReference1.User Select_UserResult) {
            this.Select_UserResult = Select_UserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_UsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Us", Namespace="http://tempuri.org/", Order=0)]
        public SC3_Alarm_Module.SC3ServiceReference1.Delete_UsRequestBody Body;
        
        public Delete_UsRequest() {
        }
        
        public Delete_UsRequest(SC3_Alarm_Module.SC3ServiceReference1.Delete_UsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_UsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id;
        
        public Delete_UsRequestBody() {
        }
        
        public Delete_UsRequestBody(string username, string password, int id) {
            this.username = username;
            this.password = password;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_UsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_UsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SC3_Alarm_Module.SC3ServiceReference1.Delete_UsResponseBody Body;
        
        public Delete_UsResponse() {
        }
        
        public Delete_UsResponse(SC3_Alarm_Module.SC3ServiceReference1.Delete_UsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_UsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Delete_UsResult;
        
        public Delete_UsResponseBody() {
        }
        
        public Delete_UsResponseBody(bool Delete_UsResult) {
            this.Delete_UsResult = Delete_UsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap>, SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SC3_Alarm_Module.SC3ServiceReference1.HelloWorldResponse SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap.HelloWorld(SC3_Alarm_Module.SC3ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SC3_Alarm_Module.SC3ServiceReference1.HelloWorldRequest inValue = new SC3_Alarm_Module.SC3ServiceReference1.HelloWorldRequest();
            inValue.Body = new SC3_Alarm_Module.SC3ServiceReference1.HelloWorldRequestBody();
            SC3_Alarm_Module.SC3ServiceReference1.HelloWorldResponse retVal = ((SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SC3_Alarm_Module.SC3ServiceReference1.HelloWorldResponse> SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap.HelloWorldAsync(SC3_Alarm_Module.SC3ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SC3_Alarm_Module.SC3ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            SC3_Alarm_Module.SC3ServiceReference1.HelloWorldRequest inValue = new SC3_Alarm_Module.SC3ServiceReference1.HelloWorldRequest();
            inValue.Body = new SC3_Alarm_Module.SC3ServiceReference1.HelloWorldRequestBody();
            return ((SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SC3_Alarm_Module.SC3ServiceReference1.Select_UserResponse SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap.Select_User(SC3_Alarm_Module.SC3ServiceReference1.Select_UserRequest request) {
            return base.Channel.Select_User(request);
        }
        
        public SC3_Alarm_Module.SC3ServiceReference1.User Select_User(string username, string password) {
            SC3_Alarm_Module.SC3ServiceReference1.Select_UserRequest inValue = new SC3_Alarm_Module.SC3ServiceReference1.Select_UserRequest();
            inValue.Body = new SC3_Alarm_Module.SC3ServiceReference1.Select_UserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            SC3_Alarm_Module.SC3ServiceReference1.Select_UserResponse retVal = ((SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap)(this)).Select_User(inValue);
            return retVal.Body.Select_UserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SC3_Alarm_Module.SC3ServiceReference1.Select_UserResponse> SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap.Select_UserAsync(SC3_Alarm_Module.SC3ServiceReference1.Select_UserRequest request) {
            return base.Channel.Select_UserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SC3_Alarm_Module.SC3ServiceReference1.Select_UserResponse> Select_UserAsync(string username, string password) {
            SC3_Alarm_Module.SC3ServiceReference1.Select_UserRequest inValue = new SC3_Alarm_Module.SC3ServiceReference1.Select_UserRequest();
            inValue.Body = new SC3_Alarm_Module.SC3ServiceReference1.Select_UserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap)(this)).Select_UserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SC3_Alarm_Module.SC3ServiceReference1.Delete_UsResponse SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap.Delete_Us(SC3_Alarm_Module.SC3ServiceReference1.Delete_UsRequest request) {
            return base.Channel.Delete_Us(request);
        }
        
        public bool Delete_Us(string username, string password, int id) {
            SC3_Alarm_Module.SC3ServiceReference1.Delete_UsRequest inValue = new SC3_Alarm_Module.SC3ServiceReference1.Delete_UsRequest();
            inValue.Body = new SC3_Alarm_Module.SC3ServiceReference1.Delete_UsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.id = id;
            SC3_Alarm_Module.SC3ServiceReference1.Delete_UsResponse retVal = ((SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap)(this)).Delete_Us(inValue);
            return retVal.Body.Delete_UsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SC3_Alarm_Module.SC3ServiceReference1.Delete_UsResponse> SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap.Delete_UsAsync(SC3_Alarm_Module.SC3ServiceReference1.Delete_UsRequest request) {
            return base.Channel.Delete_UsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SC3_Alarm_Module.SC3ServiceReference1.Delete_UsResponse> Delete_UsAsync(string username, string password, int id) {
            SC3_Alarm_Module.SC3ServiceReference1.Delete_UsRequest inValue = new SC3_Alarm_Module.SC3ServiceReference1.Delete_UsRequest();
            inValue.Body = new SC3_Alarm_Module.SC3ServiceReference1.Delete_UsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.id = id;
            return ((SC3_Alarm_Module.SC3ServiceReference1.WebService1Soap)(this)).Delete_UsAsync(inValue);
        }
    }
}
